package org.uniplovdiv.fmi.javadbaccess.ex2;

import org.uniplovdiv.fmi.javadbaccess.ex1.Connecting;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class ExecuteSQL {
    public static void main(String[] args) {

        execStatement();
        //execPreparedStatement();
        //processResultSet();
        //batchUpdate();
        //getAutoGeneratedKeys();
    }

    public static void execStatement() {

        try (Connection conn = Connecting.connectJdbc4Oracle(); Statement stmt = conn.createStatement()) {
            stmt.execute("insert into regions(region_id, region_name) values(7, 'Australia')");
            System.out.println("Rows inserted: " + stmt.getUpdateCount());
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void execPreparedStatement() {

        try (Connection conn = Connecting.connectJdbc4Oracle();
             PreparedStatement pstmt = conn.prepareStatement("update jobs set max_salary = ? where job_id like ?")) {
            pstmt.setDouble(1, 9999);
            pstmt.setString(2, "%_ACCOUNT");
            int rows = pstmt.executeUpdate();
            System.out.println("Rows updated: " + rows);

            pstmt.setDouble(1, 11999);
            pstmt.setString(2, "%_REP");
            rows = pstmt.executeUpdate();
            System.out.println("Rows updated: " + rows);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void processResultSet() {

        try (Connection conn = Connecting.connectJdbc4Oracle();
             PreparedStatement pstmt = conn.prepareStatement("select lname, hire_date from employees");
             ResultSet rset = pstmt.executeQuery()) {
            while (rset.next()) {
                System.out.println(rset.getString("lname") + " - " + rset.getDate("hire_date"));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void batchUpdate() {

        try (Connection conn = Connecting.connectJdbc4Oracle();
             PreparedStatement pstmt = conn.prepareStatement("insert into countries(country_id, name, region_id) values(?, ?, ?)")) {
            pstmt.setString(1, "RO");
            pstmt.setString(2, "Romania");
            pstmt.setInt(3, 1);
            pstmt.addBatch();

            pstmt.setString(1, "SI");
            pstmt.setString(2, "Slovenia");
            pstmt.setInt(3, 1);
            pstmt.addBatch();

            pstmt.setString(1, "RU");
            pstmt.setString(2, "Russia");
            pstmt.setInt(3, 3);
            pstmt.addBatch();

            pstmt.executeBatch();
            System.out.println("Batch updates committed.");
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    public static void getAutoGeneratedKeys() {

        String sql = "insert into employees(fname, lname, email, hire_date, job_id) "
                     + "values(?, ?, ?, sysdate, ?)";

        try (Connection conn = Connecting.connectJdbc4Oracle()) {
            PreparedStatement pstmt = conn.prepareStatement(sql, new String[]
                    {
                            "employee_id", "hire_date", "salary"
                    });
            pstmt.setString(1, "John");
            pstmt.setString(2, "Smith");
            pstmt.setString(3, "jsmith@mail.com");
            pstmt.setString(4, "IT_PROG");

            if (pstmt.executeUpdate() > 0) {
                System.out.println("New employee inserted successfully.");
                ResultSet keys = pstmt.getGeneratedKeys();

                if (keys.next()) {
                    int key = keys.getInt(1);
                    System.out.println("New employee ID = " + key);
                    String hired = keys.getString(2);
                    System.out.println("Date hired = " + hired);
                    double salary = keys.getDouble(3);
                    System.out.println("Salary = " + salary);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }

    }
}
