package org.uniplovdiv.fmi.javadbaccess.ex2;

import java.sql.*;
import org.uniplovdiv.fmi.javadbaccess.ex1.*;

public class ExecuteSQL
{
  public static void main(String[] args)
  {
    execStatement();
    //execPreparedStatement();
    //execLoopPreparedStatement();
    //processResultSet();
    //scrollSensitiveResultSet();
    //scrollableResultSet();
    //updatableResultSet();
    //updatableResultSetDelete();
    //batchUpdate();
    //getAutoGeneratedKeys();
  }

  public static void execStatement()
  {
    try (Connection conn = Connecting.connectJdbc4Oracle(); Statement stmt = conn.createStatement())
    {
      stmt.execute("insert into regions(region_id, region_name) values(5, 'Australia')");
      System.out.println("Rows inserted: " + stmt.getUpdateCount());
    }
    catch (SQLException e)
    {
      e.printStackTrace();
    }
  }

//  public static void execPreparedStatement()
//  {
//    Connection conn = null;
//    PreparedStatement pstmt = null;
//
//    try
//    {
//      Class.forName("oracle.jdbc.driver.OracleDriver");
//      conn = DriverManager.getConnection(url, username, password);
//      pstmt = conn.prepareStatement("update jobs set max_salary = ? where job_id = ?");
//      pstmt.setDouble(1, 10000);
//      pstmt.setString(2, "FI_ACCOUNT");
//      int rows = pstmt.executeUpdate();
//
//      System.out.println("Rows updated: " + rows);
//    }
//    catch (SQLException e)
//    {
//      e.printStackTrace();
//    }
//    catch (ClassNotFoundException e)
//    {
//      e.printStackTrace();
//    }
//    finally
//    {
//      try
//      {
//        pstmt.close();
//        conn.close();
//      }
//      catch (Exception e)
//      {
//      }
//    }
//  }
//
//  public static void execLoopPreparedStatement()
//  {
//    Connection conn = null;
//    PreparedStatement pstmt = null;
//
//    try
//    {
////	  Class.forName("oracle.jdbc.driver.OracleDriver");
//      DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
//      conn = DriverManager.getConnection(url, username, password);
//      pstmt = conn.prepareStatement("update jobs set max_salary = max_salary + 100 where job_id = ?");
//
//      String[] jobIds =
//      {
//        "AD_PRES", "AD_VP", "AD_ASST", "AC_MGR"
//      };
//
//      for (int i = 0; i < jobIds.length; i++)
//      {
//        pstmt.setString(1, jobIds[i]);
//        pstmt.executeUpdate();
//      }
//
//      System.out.println("Rows updated: " + jobIds.length);
//    }
//    catch (SQLException e)
//    {
//      e.printStackTrace();
//    }
//    /*	catch (ClassNotFoundException e)
//	{
//	  e.printStackTrace();
//	}
//     */ finally
//    {
//      try
//      {
//        pstmt.close();
//        conn.close();
//      }
//      catch (Exception e)
//      {
//      }
//    }
//  }
//
//  public static void processResultSet()
//  {
//    Connection conn = null;
//    PreparedStatement pstmt = null;
//    ResultSet rset = null;
//
//    try
//    {
//      DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
//      conn = DriverManager.getConnection(url, username, password);
//      pstmt = conn.prepareStatement("select last_name, hire_date from employees");
//      rset = pstmt.executeQuery();
//
//      while (rset.next())
//      {
//        System.out.println(rset.getString("last_name") + " - " + rset.getDate("hire_date"));
//      }
//    }
//    catch (SQLException e)
//    {
//      e.printStackTrace();
//    }
//    finally
//    {
//      try
//      {
//        rset.close();
//        pstmt.close();
//        conn.close();
//      }
//      catch (Exception e)
//      {
//      }
//    }
//  }
//
//  public static void scrollSensitiveResultSet()
//  {
//    Connection conn = null;
//    PreparedStatement pstmt = null;
//    ResultSet rset = null;
//
//    try
//    {
//      DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
//      conn = DriverManager.getConnection(url, username, password);
//      pstmt = conn.prepareStatement("select last_name, hire_date from employees", ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
//      rset = pstmt.executeQuery();
//
//      while (rset.next())
//      {
//        System.out.println(rset.getString("last_name") + " - " + rset.getDate("hire_date"));
//        Thread.sleep(300);
//      }
//    }
//    catch (SQLException e)
//    {
//      e.printStackTrace();
//    }
//    catch (InterruptedException e)
//    {
//      e.printStackTrace();
//    }
//    finally
//    {
//      try
//      {
//        rset.close();
//        pstmt.close();
//        conn.close();
//      }
//      catch (Exception e)
//      {
//      }
//    }
//  }
//
//  public static void scrollableResultSet()
//  {
//    Connection conn = null;
//    PreparedStatement pstmt = null;
//    ResultSet rset = null;
//
//    try
//    {
//      DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
//      conn = DriverManager.getConnection(url, username, password);
//      pstmt = conn.prepareStatement("select last_name, hire_date from employees order by last_name",
//              ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_READ_ONLY);
//      rset = pstmt.executeQuery();
//
//      rset.absolute(5);
//      System.out.println(rset.getString("last_name") + " - " + rset.getDate("hire_date"));
//
//      rset.previous();
//      System.out.println(rset.getString("last_name") + " - " + rset.getDate("hire_date"));
//
//      rset.last();
//      System.out.println(rset.getString("last_name") + " - " + rset.getDate("hire_date"));
//    }
//    catch (SQLException e)
//    {
//      e.printStackTrace();
//    }
//    finally
//    {
//      try
//      {
//        rset.close();
//        pstmt.close();
//        conn.close();
//      }
//      catch (Exception e)
//      {
//      }
//    }
//  }
//
//  public static void updatableResultSet()
//  {
//    Connection conn = null;
//    PreparedStatement pstmt = null;
//    ResultSet rset = null;
//
//    try
//    {
//      DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
//      conn = DriverManager.getConnection(url, username, password);
//      pstmt = conn.prepareStatement("select employee_id, last_name, email, hire_date, job_id from employees",
//              ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
//      rset = pstmt.executeQuery();
//
//      rset.moveToInsertRow();
//      rset.updateInt("employee_id", 1);
//      rset.updateString("last_name", "Vogl");
//      rset.updateString("email", "vogl@mail.com");
//      rset.updateDate("hire_date", new Date((new java.util.Date()).getTime()));
//      rset.updateString("job_id", "FI_ACCOUNT");
//      rset.insertRow();
//
//      System.out.println("Insert done.");
//
//      rset.beforeFirst();
//
//      while (rset.next())
//      {
//        int empId = rset.getInt("employee_id");
//        System.out.println(empId);
//
//        if (empId == 105)
//        {
//          String email = rset.getString("email");
//          System.out.println("The mail before update: " + email);
//          rset.updateString("email", "DAUSTIN@mail.com");
//          rset.updateRow();
//          System.out.println("The mail after update: " + rset.getString("email"));
//          break;
//        }
//      }
//    }
//    catch (SQLException e)
//    {
//      e.printStackTrace();
//    }
//    finally
//    {
//      try
//      {
//        rset.close();
//        pstmt.close();
//        conn.close();
//      }
//      catch (Exception e)
//      {
//      }
//    }
//  }
//
//  public static void updatableResultSetDelete()
//  {
//    Connection conn = null;
//    PreparedStatement pstmt = null;
//    ResultSet rset = null;
//
//    try
//    {
//      DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
//      conn = DriverManager.getConnection(url, username, password);
//      pstmt = conn.prepareStatement("select employee_id, last_name from employees",
//              ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
//      rset = pstmt.executeQuery();
//
//      while (rset.next())
//      {
//        int empId = rset.getInt("employee_id");
//        System.out.println(empId);
//
//        if (empId == 1)
//        {
//          System.out.println("Deleting employee: " + rset.getString("last_name"));
//          rset.deleteRow();
//          System.out.println("Done.");
//          break;
//        }
//      }
//    }
//    catch (SQLException e)
//    {
//      e.printStackTrace();
//    }
//    finally
//    {
//      try
//      {
//        rset.close();
//        pstmt.close();
//        conn.close();
//      }
//      catch (Exception e)
//      {
//      }
//    }
//  }
//
//  public static void batchUpdate()
//  {
//    Connection conn = null;
//    PreparedStatement pstmt = null;
//
//    try
//    {
//      DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
//      conn = DriverManager.getConnection(url, username, password);
//      conn.setAutoCommit(false);
//      pstmt = conn.prepareStatement("insert into countries(country_id, country_name, region_id) values(?, ?, ?)");
//
//      pstmt.setString(1, "SI");
//      pstmt.setString(2, "Slovenia");
//      pstmt.setInt(3, 1);
//      pstmt.addBatch();
//
//      pstmt.setString(1, "RU");
//      pstmt.setString(2, "Russia");
//      pstmt.setInt(3, 3);
//      pstmt.addBatch();
//
//      pstmt.executeBatch();
//      conn.commit();
//      conn.setAutoCommit(true);
//      System.out.println("Batch updates committed.");
//    }
//    catch (SQLException e)
//    {
//      e.printStackTrace();
//    }
//    finally
//    {
//      try
//      {
//        pstmt.close();
//        conn.close();
//      }
//      catch (Exception e)
//      {
//      }
//    }
//  }
//
//  public static void getAutoGeneratedKeys()
//  {
//    Connection conn = null;
//    PreparedStatement pstmt = null;
//
//    try
//    {
//      String sql = "insert into employees(first_name, last_name, email, hire_date, job_id) "
//              + "values(?, ?, ?, sysdate, ?)";
//
//      DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
//      conn = DriverManager.getConnection(url, username, password);
//      pstmt = conn.prepareStatement(sql, new String[]
//      {
//        "employee_id"
//      });
//      pstmt.setString(1, "Vasil");
//      pstmt.setString(2, "Gyrov");
//      pstmt.setString(3, "gehdk@-plovdiv.bg");
//      pstmt.setString(4, "IT_PROG");
//
//      if (pstmt.executeUpdate() > 0)
//      {
//        System.out.println("New employee inserted successfully.");
//        ResultSet keys = pstmt.getGeneratedKeys();
//
//        if (keys.next())
//        {
//          int key = keys.getInt(1);
//          System.out.println("New employee ID = " + key);
//        }
//      }
//    }
//    catch (SQLException e)
//    {
//      e.printStackTrace();
//    }
//    finally
//    {
//      try
//      {
//        pstmt.close();
//        conn.close();
//      }
//      catch (Exception e)
//      {
//      }
//    }
//  }
}
